######################################################################
# Automatically generated by qmake (3.1) Mon Nov 7 17:07:58 2022
######################################################################

TEMPLATE = app
TARGET = test
INCLUDEPATH += .
CONFIG += debug

RESOURCES += ../images.qrc
FORMS += ../assets/ui/main.ui
FORMS += ../assets/ui/cheat.ui

QT += gui
QT += widgets

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
SOURCES += $$files($$PWD/*.cpp)
SOURCES += $$files($$PWD/../src/*.cpp)
SOURCES -= $$PWD/../src/main.cpp
HEADERS += $$files($$PWD/*.h)
HEADERS += $$files($$PWD/../src/*.h)
